import React from "react";
import Check from "@/components/ui/icon/check";
import { X } from "lucide-react";
export default function Page() {
  return (
    <div>
      <h2 className="text-base font-semibold mt-6 mb-2">Edge Cases</h2>
      <p> this page contains a list of found Edge Cases</p>
      <table className="m-auto my-8 text-left" cellPadding={8}>
        <thead>
          <tr className="border-t-[1px]">
            <th>Index</th>
            <th>Case</th>
            <th>expected Behaviour</th>
            <th>matches actual behaviour</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-t-[1px]">
            <td>1</td>
            <td>Move to a date already generated by RRULE</td>
            <td>
              exdate the original date, upsert todo instance row with overrides
            </td>
            <td>
              <Check className="w-4 h-4 text-lime m-auto" />
            </td>
          </tr>
          <tr className="border-t-[1px]">
            <td>2</td>
            <td>Move to a date already overridden</td>
            <td>
              exdate the original date, upsert todo instance row with overrides
            </td>
            <td>
              <Check className="w-4 h-4 text-lime m-auto" />
            </td>
          </tr>
          <tr className="border-t-[1px]">
            <td>3</td>
            <td>Move outside the recurrence range</td>
            <td>
              identifies which original RRULE occurrence this override belongs
              to
            </td>
            <td>
              <X className="w-4 h-4 text-red m-auto" />
            </td>
          </tr>
          <tr className="border-y-[1px]">
            <td>4</td>
            <td>Move to a date that was previously EXDATEd</td>
            <td>remove the moved-to date from exdates</td>
            <td>
              <X className="w-4 h-4 text-red m-auto" />
            </td>
          </tr>
          <tr className="border-y-[1px]">
            <td>5</td>
            <td>Move back to original date</td>
            <td>Changed start time for this occurrence</td>
            <td>
              <X className="w-4 h-4 text-red m-auto" />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
