import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import QueryProvider from "@/providers/QueryProvider";
import { SessionProvider } from "next-auth/react";
import "@/app/globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      </head> */}
      <QueryProvider>
        <SessionProvider>
          <body className={`${poppins.variable} antialiased`}>{children}</body>
        </SessionProvider>
      </QueryProvider>
    </html>
  );
}
