import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "@/app/globals.css";
import { prisma } from "@/lib/prisma/client";
import { auth } from "../auth";
import { UserPreferencesProvider } from "@/providers/UserPreferencesProvider";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
  params,
}: Props) {
  const { locale } = await params;
  const messages = await getMessages();
  const session = await auth();
  async function getInitialPreferences() {
    try {
      const preferences = await prisma.userPreferences.findUnique({ where: { userID: session!.user.id } })
      return preferences
    } catch {
      return null;
    }
  }
  const initialPreferences = await getInitialPreferences();
  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <title>Sanity</title>
      </head>
      <SessionProvider>
        <body className={`${poppins.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider messages={messages}>
              <UserPreferencesProvider initialPreferences={initialPreferences}>
                {children}
              </UserPreferencesProvider>
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </SessionProvider>
    </html>
  );
}